import { localizePath } from '@oathly/i18n';
import type { Metadata } from 'next';
import Link from 'next/link';

import { Contact, LegalPage, legalLink, List, Section } from '@/components/legal/legal-page';
import { getT } from '@/lib/i18n';
import { operator } from '@/lib/legal';

const title = 'Terms of use';

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: `${title} | Oathly`,
    description:
      'The terms for using Oathly: what it is and is not, accounts, plans and payment, and what each of us is responsible for.',
    alternates: { canonical: '/terms' },
  };
}

export default async function TermsPage({ params }: PageProps<'/[locale]/terms'>) {
  const { locale, t } = await getT(params);
  const who = operator();
  return (
    <LegalPage t={t} path="/terms" title={title}>
      <p>
        These terms are the agreement between you and {who.name} for using Oathly, on the website
        and in the phone apps. By creating an account you accept them.
      </p>

      <Section title="What Oathly is, and is not">
        <List>
          <li>
            Oathly is a study aid for citizenship tests. It is independent and is{' '}
            <strong>not affiliated with, or endorsed by, any government</strong>. It cannot book
            your test, and nothing in it is an official decision or legal advice.
          </li>
          <li>
            Practice questions are written from official study material and checked against it by a
            reviewer, with the source linked. Rules and tests change: always confirm what applies to
            you on the official website. The questions you are asked on the day may be worded
            differently.
          </li>
          <li>
            The readiness estimate is an estimate.{' '}
            <strong>Oathly does not guarantee that you will pass</strong>, and a pass in a mock exam
            is not a pass in the real one.
          </li>
          <li>
            AI explanations and the AI tutor are generated by a language model from the official
            material. They can be wrong. Where it matters, check the source.
          </li>
        </List>
      </Section>

      <Section title="Your account">
        <p>
          You need an account to save progress. Keep access to the email address you sign in with:
          it is how you get back in. You are responsible for what is done with your account. You
          must be at least 16 to use Oathly. You can delete your account at any time:{' '}
          <Link href={localizePath(locale, '/delete-account')} className={legalLink}>
            how to delete your account
          </Link>
          .
        </p>
      </Section>

      <Section title="Plans and payment">
        <List>
          <li>Oathly can be used free of charge, with limits shown in the app.</li>
          <li>
            <strong>Pro</strong> is a subscription, monthly or yearly. It renews automatically at
            the price shown when you bought it until you cancel. You can cancel at any time; you
            keep Pro until the end of the period you have paid for.
          </li>
          <li>
            A <strong>Country Pass</strong> is a single payment that opens one country&apos;s
            questions for as long as Oathly offers that country. It does not renew.
          </li>
          <li>
            Bought on the website, a plan is paid through Stripe and managed from the Plans page.
            Bought in a phone app, it is paid through the App Store or Google Play, is managed in
            your phone&apos;s subscription settings, and is also subject to that store&apos;s terms,
            including its rules on refunds.
          </li>
          <li>
            Where the law gives you a right to withdraw from a purchase or to a refund, these terms
            do not take it away.
          </li>
          <li>
            Prices can change. A change applies to a subscription from its next renewal, and you
            will be told beforehand.
          </li>
        </List>
      </Section>

      <Section title="Organizations">
        <p>
          A school, law firm or other organization can buy seats and invite learners. If you accept
          an invitation, the organization&apos;s administrators can see your readiness and activity
          as described in the{' '}
          <Link href={localizePath(locale, '/privacy')} className={legalLink}>
            privacy policy
          </Link>
          , and you study on Pro while you hold one of its seats. The organization decides who holds
          its seats and can remove you; you can leave at any time. An organization is responsible
          for having the right to invite the people it invites.
        </p>
      </Section>

      <Section title="Fair use">
        <p>You agree not to:</p>
        <List>
          <li>copy, scrape or republish Oathly&apos;s questions, explanations or other content;</li>
          <li>share your account, or resell access to it;</li>
          <li>try to get around a plan&apos;s limits, or interfere with the service;</li>
          <li>use the tutor for anything other than preparing for the test.</li>
        </List>
        <p>We may suspend an account that does, after telling you why where we can.</p>
      </Section>

      <Section title="Content and ownership">
        <p>
          The app, its questions, explanations and design belong to {who.name} or its licensors.
          Official study material belongs to whoever published it and is quoted and linked as a
          source. You may use Oathly for your own study; that is the only licence these terms give.
          What you type into the app remains yours; you allow us to process it to provide the
          service.
        </p>
      </Section>

      <Section title="Availability and changes">
        <p>
          We work to keep Oathly available and correct, but it is provided as it is: it may be
          interrupted, and content may be changed, corrected or withdrawn, for example when an
          official test changes.
        </p>
      </Section>

      <Section title="Liability">
        <p>
          Nothing in these terms limits liability that cannot be limited by law, or the rights you
          have as a consumer. Beyond that, {who.name} is not liable for losses that were not a
          foreseeable result of our breaking these terms, for the outcome of your test or
          application, or for more than you paid us in the twelve months before the claim.
        </p>
      </Section>

      <Section title="Changes to these terms">
        <p>
          When these terms change, the date at the top changes with them. For a change that matters,
          we will tell you in the app before it takes effect; carrying on using Oathly after that
          means you accept it.
        </p>
      </Section>

      <Section title="Law and contact">
        {who.jurisdiction && (
          <p>
            These terms are governed by the law of {who.jurisdiction}. If you are a consumer, you
            also keep the protection of the mandatory law of the country where you live.
          </p>
        )}
        <p>Questions about these terms go to:</p>
        <Contact operator={who} />
      </Section>
    </LegalPage>
  );
}
